version: '2'
services:
  mytomcat:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - redis
  mytomcat2:
    build: ./
    ports:
      - "9090:8080"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
  proxy:
    image: nginx
    ports:
      - "3000:3000"
    links:
      - mytomcat
    depends_on:
      - mytomcat
      - mytomcat2
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
